# Generated by Django 3.2.13 on 2023-01-16 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Skills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skillName', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('experince', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=40)),
                ('lastName', models.CharField(max_length=40)),
                ('idNumber', models.PositiveIntegerField()),
                ('organ', models.CharField(max_length=100)),
                ('job', models.CharField(max_length=60)),
                ('employDate', models.DateField()),
                ('birthDate', models.DateField()),
                ('pesonalPhone', models.PositiveIntegerField()),
                ('jobPhone', models.PositiveIntegerField()),
            ],
        ),
    ]
